[project]
name = "hw01-triton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "jupytext>=1.17.3",
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "triton>=3.4.0",
]
